import "./bootstrap";

import {
    createIcons,
    User,
    Star,
    Mail,
    Lock,
    ArrowRight,
    MoveLeft,
    Instagram,
    Facebook,
    Search,
    House,
    BookUp,
    BookOpen,
    ListFilter,
    Bookmark,
    MessageSquare,
    LogOut,
    ChevronDown,
    History,
    FileText,
    RotateCcw,
} from "lucide";

createIcons({
    icons: {
        User,
        Star,
        Mail,
        Lock,
        ArrowRight,
        MoveLeft,
        Instagram,
        Facebook,
        Search,
        House,
        BookUp,
        BookOpen,
        ListFilter,
        Bookmark,
        MessageSquare,
        LogOut,
        ChevronDown,
        History,
        FileText,
        RotateCcw,
    },
});
